module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  anchor_link: 0
  asset_injector: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_order: 0
  commerce_price: 0
  commerce_product: 0
  commerce_shipping: 0
  commerce_store: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_embed: 0
  entity_print: 0
  entity_reference_revisions: 0
  facets: 0
  fakeobjects: 0
  field: 0
  field_group: 0
  field_ui: 0
  fieldblock: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  forward: 0
  geolocation: 0
  google_analytics: 0
  hal: 0
  help: 0
  history: 0
  honeypot: 0
  iframe: 0
  image: 0
  image_effects: 0
  image_widget_crop: 0
  inline_entity_form: 0
  jsonapi: 0
  language: 0
  layout_discovery: 0
  link: 0
  mailsystem: 0
  media_entity: 0
  media_entity_image: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_ipe: 0
  path: 0
  physical: 0
  profile: 0
  quickedit: 0
  rdf: 0
  realname: 0
  redirect: 0
  redis: 0
  reroute_email: 0
  rules: 0
  scheduled_updates: 0
  schemata: 0
  schemata_json_schema: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  search_api_solr_defaults: 0
  serialization: 0
  services: 0
  shortcut: 0
  slick: 0
  slick_ui: 0
  smtp: 0
  social_media_links: 0
  state_machine: 0
  switch_page_theme: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_embed_views: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  video: 0
  video_embed_field: 0
  views_bootstrap: 0
  views_infinite_scroll: 0
  views_templates: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  webform_views: 0
  workbench_email: 0
  workbench_moderation: 0
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
